# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_CLK_STARFIVE)	+= clk-starfive.o

obj-$(CONFIG_CLK_STARFIVE_JH7100)	+= clk-starfive-jh7100.o
obj-$(CONFIG_CLK_STARFIVE_JH7100_AUDIO)	+= clk-starfive-jh7100-audio.o

obj-$(CONFIG_CLK_STARFIVE_JH7110_SYS)	+= clk-starfive-jh7110-sys.o
